---
title: Works
---

## **学術論文 (査読あり)**
論文がダウンロードできない際は，Preprintと書かれた部分をクリックしてくだされば，そこから出版前の原稿を入手できます。

#### **Takano, R.** & Nomura, M. Awe liberates the feeling that "my body is mine" [**Cognition and Emotion**](https://doi.org/10.1080/02699931.2020.1862765), Advance online publication. [Preprint](https://osf.io/f6vd3/), [OSF](https://osf.io/3w2er/)

#### **高野了太**・高史明・野村理朗. 日本語版右翼権威主義尺度の作成. [**心理学研究**](https://doi.org/10.4992/jjpsy.91.19225), 91(6), 398-408.

#### **Takano, R.** & Nomura, M. Neural representations of awe: Distinguishing the common and distinct neural mechanisms [**Emotion**](https://doi.org/10.1037/emo0000771), Advance online publication. [Preprint](https://psyarxiv.com/qk8dn/), [OSF](https://osf.io/nxy7a/)

#### **Takano, R.** & Nomura, M. (2019). Anodal transcranial Direct Current Stimulation of the Right Temporoparietal Junction Enhances the Self-effacing Bias in Japanese Individuals [**Culture and Brain**]("https://doi.org/10.1007/s40167-018-0064-4"), 7, 80-91. 

<br>

## **フェローシップ，賞罰**

#### 日本心理学会第83回大会 学術大会優秀発表賞 2019年

#### 日本学術振興会科学研究費 特別研究員奨励費 2019年-2022年

#### 京都大学教育学研究科グローバル教育展開オフィス 国際学会発表支援 2018年

#### 日本心理学会 国際会議等参加者旅費補助 2017年
<br>

## **学会発表 (国際学会)**

### **ポスター発表**

#### **Takano, R.** & Nomura, M. (2020). Awe Liberates the Sense of Self: A Small-Self Increases Sensitivity to the Rubber-Hand Illusion. _APS Virtual Poster Showcase_. June-September.

#### **Takano, R.** & Nomura, M. (2019). Neural Basis of Aesthetic Emotion: Origin of Prosocial Behavior and Aggression. _6th Congress of Asian College of Neuropsychopharmacology_, Fukuoka, Japan. Oct 10-Oct 12.

#### Hiraoka, D., **Takano, R.**, Kihara, M., Hayashi, M., & Nomura, M. (2019).  Cognitive load induces maternal approach behaviour to infant vocalisation, _British Psychological Society_, Stoke on Trent, UK, September 4.

#### **Takano, R.** & Nomura, M. (2018). Interdependent worldviews evoked by threat-based awe in Japan. _The 24th Congress of the International Association for Cross-Cultural Psychology_, Guelph, Canada. July 1-July 5.

#### **Takano, R.** & Nomura, M. (2018). The dark side of awe: From the perspective of intergroup conflict. _The 19th Annual Meeting of Society for Personality and Social Psychology_, Atlanta, Georgia, USA, March 1-3.
<br>

## **学会発表 (国内学会)**

### **口頭発表**

#### **高野了太**. (2020). 畏敬の念と自己. 日本心理学会第84回大会, 東洋大学 (web開催). (シンポジウム「ポジティブ心理学における多様な感情経験」話題提供). 9月8日-11月2日.

#### **高野了太** . (2018). 畏敬の念からみる「無心」. 日本心理学会第82回大会, 仙台国際センター. (シンポジウム『「無心」の心理学』話題提供). 

### **ポスター発表**

#### **高野了太**・野村理朗. (2020). 自他の社会的地位が虚偽情報による態度の修正に及ぼす影響. 日本社会心理学会第61回大会, 学習院大学 (web開催). 11月7日-11月8日.

#### **高野了太**・野村理朗. (2020). 畏敬の念が自己を手放す―ラバーハンド錯覚を用いた検討―. 日本心理学会第84回大会, 東洋大学 (web開催). 9月8日-11月2日.

#### 澤田和輝・**高野了太**・野村理朗. (2020). 特性畏敬と安静時脳活動の関連. 日本心理学会第84回大会, 東洋大学 (web開催). 9月8日-11月2日.

#### **高野了太**・野村理朗. (2019). 「畏敬の念」が外集団不寛容性に与える影響. 日本社会心理学会第60回大会, 立正大学, 11月9-10日.

#### **高野了太**・野村理朗. (2019). 畏敬の念が内集団に対する協力的態度に及ぼす影響. 日本心理学会第83回大会, 立命館大学, 9月11-13日. 【優秀発表賞】

#### 平岡大樹・**高野了太**・木原真帆・林実穂・野村理朗. (2019). 認知的負荷が乳児の音声に対する接近行動・心拍を増加させる，日本赤ちゃん学会第19回学術集会，聖心女子大学，7月6日

#### **高野了太**・野村理朗. (2018). 「畏敬の念」の神経基盤に関する検討―自己概念変容の観点から―. 日本心理学会第82回大会, 仙台国際センター, 9月25-27日. 

#### **高野了太**・野村理朗. (2018). 畏敬の念は利他的行動を促進するのか？―認知的スキーマ更新の観点から―. 日本社会心理学会第59回大会, 追手門学院大学, 8月28-29日. 

#### 伊川美保・綾部宏明・松岡真由子・平岡大樹・西山慧・**高野了太**・楠見孝. (2017). 統計リテラシー日本語版尺度の妥当性と信頼性の検討. 日本教育心理学会第59回総会, 名古屋国際会議場, 10月7日-9日.


<br>


## **招待講演**
#### 大阪大学，2018年12月
<br>

## **準備中**

#### **Takano. R.** & Nomura, M. RWA and Spirituality (under review)
#### **Takano. R.**, Sawada, K., & Nomura, M. Awe and Social behavior (under review)
#### Imada, H. & **Takano. R.** Awe and Social cognition (in preparation)




